// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VisitorManagementSystem.Data;

#nullable disable

namespace VisitorManagementSystem.Migrations
{
    [DbContext(typeof(VMSDbContext))]
    [Migration("20251028030841_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VisitorManagementSystem.Models.CarriedMtrlModel.CarriedMaterialModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("VisitDate")
                        .HasColumnType("date");

                    b.Property<string>("VisitorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cMtrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("cMtrlQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CarriedMaterial_ByVisitor");
                });

            modelBuilder.Entity("VisitorManagementSystem.Models.CompanySiteModel", b =>
                {
                    b.Property<int>("SiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiteId"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("SiteName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SiteId");

                    b.ToTable("SiteMaster");

                    b.HasData(
                        new
                        {
                            SiteId = 1,
                            CountryId = 1,
                            SiteName = "Nagpur HQ"
                        },
                        new
                        {
                            SiteId = 2,
                            CountryId = 1,
                            SiteName = "Mumbai Office"
                        },
                        new
                        {
                            SiteId = 3,
                            CountryId = 1,
                            SiteName = "Delhi Branch"
                        },
                        new
                        {
                            SiteId = 4,
                            CountryId = 2,
                            SiteName = "New York Office"
                        },
                        new
                        {
                            SiteId = 5,
                            CountryId = 3,
                            SiteName = "London Office"
                        });
                });

            modelBuilder.Entity("VisitorManagementSystem.Models.CountryModel", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            CountryName = "India"
                        },
                        new
                        {
                            CountryId = 2,
                            CountryName = "United States"
                        },
                        new
                        {
                            CountryId = 3,
                            CountryName = "United Kingdom"
                        },
                        new
                        {
                            CountryId = 4,
                            CountryName = "Germany"
                        },
                        new
                        {
                            CountryId = 5,
                            CountryName = "Japan"
                        });
                });

            modelBuilder.Entity("VisitorManagementSystem.Models.DeptData", b =>
                {
                    b.Property<int>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeptId"));

                    b.Property<string>("DeptHOD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeptName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeptId");

                    b.ToTable("Department");

                    b.HasData(
                        new
                        {
                            DeptId = 1,
                            DeptHOD = "John Smith",
                            DeptName = "IT"
                        },
                        new
                        {
                            DeptId = 2,
                            DeptHOD = "Sarah Johnson",
                            DeptName = "Human Resources"
                        },
                        new
                        {
                            DeptId = 3,
                            DeptHOD = "Michael Brown",
                            DeptName = "Finance"
                        },
                        new
                        {
                            DeptId = 4,
                            DeptHOD = "Emily Davis",
                            DeptName = "Operations"
                        },
                        new
                        {
                            DeptId = 5,
                            DeptHOD = "David Wilson",
                            DeptName = "Marketing"
                        },
                        new
                        {
                            DeptId = 6,
                            DeptHOD = "Jessica Martinez",
                            DeptName = "Sales"
                        });
                });

            modelBuilder.Entity("VisitorManagementSystem.Models.EmpData", b =>
                {
                    b.Property<int>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpId"));

                    b.Property<int>("DeptId")
                        .HasColumnType("int");

                    b.Property<string>("EmpContactNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteId")
                        .HasColumnType("int");

                    b.HasKey("EmpId");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            EmpId = 1,
                            DeptId = 1,
                            EmpContactNo = "+91-9876543210",
                            EmpEmail = "admin@company.com",
                            EmpName = "Admin User",
                            KO = "ADM001",
                            Password = "Admin@123",
                            Role = "Admin",
                            SiteId = 1
                        },
                        new
                        {
                            EmpId = 2,
                            DeptId = 1,
                            EmpContactNo = "+91-9876543211",
                            EmpEmail = "rajesh.kumar@company.com",
                            EmpName = "Rajesh Kumar",
                            KO = "IT001",
                            Password = "User@123",
                            Role = "Security",
                            SiteId = 1
                        },
                        new
                        {
                            EmpId = 3,
                            DeptId = 2,
                            EmpContactNo = "+91-9876543212",
                            EmpEmail = "priya.sharma@company.com",
                            EmpName = "Priya Sharma",
                            KO = "HR001",
                            Password = "User@123",
                            Role = "Employee",
                            SiteId = 1
                        },
                        new
                        {
                            EmpId = 4,
                            DeptId = 3,
                            EmpContactNo = "+91-9876543213",
                            EmpEmail = "amit.patel@company.com",
                            EmpName = "Amit Patel",
                            KO = "FIN001",
                            Password = "User@123",
                            Role = "Employee",
                            SiteId = 2
                        },
                        new
                        {
                            EmpId = 5,
                            DeptId = 4,
                            EmpContactNo = "+91-9876543214",
                            EmpEmail = "sneha.reddy@company.com",
                            EmpName = "Sneha Reddy",
                            KO = "OPS001",
                            Password = "User@123",
                            Role = "Security",
                            SiteId = 1
                        });
                });

            modelBuilder.Entity("VisitorManagementSystem.Models.FavVisitorsModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("EmpId")
                        .HasColumnType("int");

                    b.Property<bool>("Favorite")
                        .HasColumnType("bit");

                    b.Property<string>("VisitorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("FavVisitors");
                });

            modelBuilder.Entity("VisitorManagementSystem.Models.VTypeModel", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeId"));

                    b.Property<string>("VisitorType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypeId");

                    b.ToTable("VisitorType");
                });

            modelBuilder.Entity("VisitorManagementSystem.Models.VisitingDetailsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Approval")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanyDepartment")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("CompanySite")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("RegistrationDate")
                        .HasColumnType("date");

                    b.Property<string>("SafetyStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityApproval")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("ToDate")
                        .HasColumnType("date");

                    b.Property<int?>("TypeId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<bool>("VisitArea")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("VisitDate")
                        .HasColumnType("date");

                    b.Property<string>("VisitTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisitorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VisitDetails");
                });

            modelBuilder.Entity("VisitorManagementSystem.Models.VisitorMasterModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DOB")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdProof")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdProofNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisitorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VisitorMaster");
                });

            modelBuilder.Entity("VisitorManagementSystem.Models.VisitorTransactionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CheckIn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckOut")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("VDetails_Id")
                        .HasColumnType("int");

                    b.Property<string>("VisitorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VisitorTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
